name: Generate PDFs from resource Markdown (create PR)

on:
  workflow_dispatch: {}

permissions:
  contents: write
  pull-requests: write

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install dependencies
        run: |
          npm ci || npm install
          npm install markdown-it puppeteer fs-extra --no-audit --no-fund

      - name: Generate PDFs
        run: node scripts/generate-pdfs.js

      - name: Create pull request with generated PDFs
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: chore: generate PDFs from resource markdown
          title: chore: generate PDFs from resource markdown
          body: This PR adds generated PDF versions of the resource markdown files.
          branch: generated/pdfs-${{ github.run_id }}
          labels: automated